-- Music genres' seed --
INSERT INTO genres (name, slug) VALUES
('Alternative', 'alternative'),
('Art Punk', 'art_punk'),
('Alternative Rock', 'alternative_rock'),
('Britpunk', 'britpunk'),
('College Rock', 'college_rock'),
('Crossover Thrash', 'crossover_thrash'),
('Crust Punk', 'crust_punk'),
('Thx Haug', 'thx_haug'),
('Emotional Hardcore', 'emotional_hardcore'),
('Emo', 'emo'),
('Emocore', 'emocore'),
('Experimental Rock', 'experimental_rock'),
('Folk Punk', 'folk_punk'),
('Goth', 'goth'),
('Gothic Rock', 'gothic_rock'),
('Grunge', 'grunge'),
('Hardcore Punk', 'hardcore_punk'),
('Hard Rock', 'hard_rock'),
('Indie Rock', 'indie_rock'),
('Lo-fi', 'lofi'),
('Musique Concrète', 'musique_concrete'),
('New Wave', 'new_wave'),
('Progressive Rock', 'progressive_rock'),
('Punk', 'punk'),
('Shoegaze', 'shoegaze'),
('Steampunk', 'steampunk'),
('Anime', 'anime'),
('Blues', 'blues'),
('Acoustic Blues', 'acoustic_blues'),
('African Blues', 'african_blues'),
('Blues Rock', 'blues_rock'),
('Blues Shouter', 'blues_shouter'),
('British Blues', 'british_blues'),
('Canadian Blues', 'canadian_blues'),
('Chicago Blues', 'chicago_blues'),
('Classic Blues', 'classic_blues'),
('Classic Female Blues', 'classic_female_blues'),
('Contemporary Blues', 'contemporary_blues'),
('Contemporary R&B', 'contemporary_rb'),
('Country Blues', 'country_blues'),
('Dark Blues', 'dark_blues'),
('Delta Blues', 'delta_blues'),
('Detroit Blues', 'detroit_blues'),
('Doom Blues', 'doom_blues'),
('Electric Blues', 'electric_blues'),
('Folk Blues', 'folk_blues'),
('Gospel Blues', 'gospel_blues'),
('Harmonica Blues', 'harmonica_blues'),
('Hill Country Blues', 'hill_country_blues'),
('Hokum Blues', 'hokum_blues'),
('Jazz Blues', 'jazz_blues'),
('Jump Blues', 'jump_blues'),
('Kansas City Blues', 'kansas_city_blues'),
('Louisiana Blues', 'louisiana_blues'),
('Memphis Blues', 'memphis_blues'),
('Modern Blues', 'modern_blues'),
('New Orlean Blues', 'new_orlean_blues'),
('NY Blues', 'ny_blues'),
('Piano Blues', 'piano_blues'),
('Piedmont Blues', 'piedmont_blues'),
('Punk Blues', 'punk_blues'),
('Ragtime Blues', 'ragtime_blues'),
('Rhythm Blues', 'rhythm_blues'),
('Soul Blues', 'soul_blues'),
('St. Louis Blues', 'st_louis_blues'),
('Swamp Blues', 'swamp_blues'),
('Texas Blues', 'texas_blues'),
('Urban Blues', 'urban_blues'),
('Vandeville', 'vandeville'),
('West Coast Blues', 'west_coast_blues'),
('Zydeco', 'zydeco'),
('Children’s Music', 'childrens_music'),
('Lullabies', 'lullabies'),
('Sing-Along', 'singalong'),
('Stories', 'stories'),
('Classical', 'classical'),
('Avant-Garde', 'avantgarde'),
('Ballet', 'ballet'),
('Baroque', 'baroque'),
('Cantata', 'cantata'),
('Chamber Music', 'chamber_music'),
('String Quartet', 'string_quartet'),
('Chant', 'chant'),
('Choral', 'choral'),
('Classical Crossover', 'classical_crossover'),
('Concerto', 'concerto'),
('Concerto Grosso', 'concerto_grosso'),
('Contemporary Classical', 'contemporary_classical'),
('Early Music', 'early_music'),
('Expressionist', 'expressionist'),
('High Classical', 'high_classical'),
('Impressionist', 'impressionist'),
('Mass Requiem', 'mass_requiem'),
('Medieval', 'medieval'),
('Minimalism', 'minimalism'),
('Modern Composition', 'modern_composition'),
('Modern Classical', 'modern_classical'),
('Opera', 'opera'),
('Oratorio', 'oratorio'),
('Orchestral', 'orchestral'),
('Organum', 'organum'),
('Renaissance', 'renaissance'),
('Romantic', 'romantic'),
('Sonata', 'sonata'),
('Symphonic', 'symphonic'),
('Symphony', 'symphony'),
('Twelve-tone', 'twelvetone'),
('Wedding Music', 'wedding_music'),
('Comedy', 'comedy'),
('Novelty', 'novelty'),
('Parody Music', 'parody_music'),
('Weird Al!', 'weird_al'),
('Stand-up Comedy', 'standup_comedy'),
('Vaudeville', 'vaudeville'),
('Commercial', 'commercial'),
('Jingles', 'jingles'),
('TV Themes', 'tv_themes'),
('Country', 'country'),
('Alternative Country', 'alternative_country'),
('Americana', 'americana'),
('Australian Country', 'australian_country'),
('Bakersfield Sound', 'bakersfield_sound'),
('Bluegrass', 'bluegrass'),
('Progressive Bluegrass', 'progressive_bluegrass'),
('Reactionary Bluegrass', 'reactionary_bluegrass'),
('Cajun Fiddle Tunes', 'cajun_fiddle_tunes'),
('Christian Country', 'christian_country'),
('Classic Country', 'classic_country'),
('Close Harmony', 'close_harmony'),
('Contemporary Bluegrass', 'contemporary_bluegrass'),
('Contemporary Country', 'contemporary_country'),
('Country Gospel', 'country_gospel'),
('Country Pop', 'country_pop'),
('Country Rap', 'country_rap'),
('Country Rock', 'country_rock'),
('Country Soul', 'country_soul'),
('Cowboy', 'cowboy'),
('Western', 'western'),
('Cowpunk', 'cowpunk'),
('Dansband', 'dansband'),
('Honky Tonk', 'honky_tonk'),
('Franco-Country', 'francocountry'),
('Gulf & Western', 'gulf__western'),
('Hellbilly Music', 'hellbilly_music'),
('Instrumental Country', 'instrumental_country'),
('Lubbock Sound', 'lubbock_sound'),
('Nashville Sound', 'nashville_sound'),
('Neotraditional Country', 'neotraditional_country'),
('Outlaw Country', 'outlaw_country'),
('Progressive', 'progressive'),
('Psychobilly', 'psychobilly'),
('Punkabilly', 'punkabilly'),
('Red Dirt', 'red_dirt'),
('Sertanejo', 'sertanejo'),
('Texas County', 'texas_county'),
('Traditional Bluegrass', 'traditional_bluegrass'),
('Traditional Country', 'traditional_country'),
('Truck-Driving Country', 'truckdriving_country'),
('Urban Cowboy', 'urban_cowboy'),
('Western Swing', 'western_swing'),
('Dance', 'dance'),
('Club', 'club'),
('Club Dance', 'club_dance'),
('Breakcore', 'breakcore'),
('Breakbeat', 'breakbeat'),
('Breakstep', 'breakstep'),
('4-Beat', '4beat'),
('Acid Breaks', 'acid_breaks'),
('Baltimore Club', 'baltimore_club'),
('Big Beat', 'big_beat'),
('Breakbeat Hardcore', 'breakbeat_hardcore'),
('Broken Beat', 'broken_beat'),
('Florida Breaks', 'florida_breaks'),
('Nu Skool Breaks', 'nu_skool_breaks'),
('Brostep', 'brostep'),
('Chillstep', 'chillstep'),
('Deep House', 'deep_house'),
('Dubstep', 'dubstep'),
('Electro House', 'electro_house'),
('Electroswing', 'electroswing'),
('Exercise', 'exercise'),
('Future Garage', 'future_garage'),
('Garage', 'garage'),
('Glitch Hop', 'glitch_hop'),
('Glitch Pop', 'glitch_pop'),
('Grime', 'grime'),
('Hardcore', 'hardcore'),
('Bouncy House', 'bouncy_house'),
('Bouncy Techno', 'bouncy_techno'),
('Digital Hardcore', 'digital_hardcore'),
('Doomcore', 'doomcore'),
('Dubstyle', 'dubstyle'),
('Gabber', 'gabber'),
('Happy Hardcore', 'happy_hardcore'),
('Hardstyle', 'hardstyle'),
('Jumpstyle', 'jumpstyle'),
('Makina', 'makina'),
('Speedcore', 'speedcore'),
('Terrorcore', 'terrorcore'),
('Uk Hardcore', 'uk_hardcore'),
('Hard Dance', 'hard_dance'),
('Hi-NRG', 'hinrg'),
('Eurodance', 'eurodance'),
('Horrorcore', 'horrorcore'),
('Thx Matt', 'thx_matt'),
('House', 'house'),
('Acid House', 'acid_house'),
('Chicago House', 'chicago_house'),
('Diva House', 'diva_house'),
('Dutch House', 'dutch_house'),
('Freestyle House', 'freestyle_house'),
('French House', 'french_house'),
('Funky House', 'funky_house'),
('Ghetto House', 'ghetto_house'),
('Hardbag', 'hardbag'),
('Hip House', 'hip_house'),
('Italo House', 'italo_house'),
('Latin House', 'latin_house'),
('Minimal House', 'minimal_house'),
('Progressive House', 'progressive_house'),
('Trance', 'trance'),
('Rave Music', 'rave_music'),
('Swing House', 'swing_house'),
('Tech House', 'tech_house'),
('Tribal House', 'tribal_house'),
('Tropical House', 'tropical_house'),
('UK Hard House', 'uk_hard_house'),
('US Garage', 'us_garage'),
('Vocal House', 'vocal_house'),
('Jackin House', 'jackin_house'),
('Jungle', 'jungle'),
('Drum’n’bass', 'drumnbass'),
('Liquid Dub', 'liquid_dub'),
('Regstep', 'regstep'),
('Techno', 'techno'),
('Acid Techno', 'acid_techno'),
('Detroit Techno', 'detroit_techno'),
('Free Tekno', 'free_tekno'),
('Ghettotech', 'ghettotech'),
('Minimal', 'minimal'),
('Nortec', 'nortec'),
('Schranz', 'schranz'),
('Techno-Dnb', 'technodnb'),
('Technopop', 'technopop'),
('Tecno Brega', 'tecno_brega'),
('Toytown Techno', 'toytown_techno'),
('Trance', 'trance'),
('Acid Trance', 'acid_trance'),
('Acid-House', 'acidhouse'),
('Classic Trance', 'classic_trance'),
('Dark Psy', 'dark_psy'),
('Dream Trance', 'dream_trance'),
('Goa Trance', 'goa_trance'),
('Dark Psytrance', 'dark_psytrance'),
('Full on', 'full_on'),
('Psybreaks', 'psybreaks'),
('Psyprog', 'psyprog'),
('Suomisaundi', 'suomisaundi'),
('Hard Trance', 'hard_trance'),
('Prog. Trance', 'prog_trance'),
('Psy-Trance', 'psytrance'),
('Minimal Techno', 'minimal_techno'),
('Tech Trance', 'tech_trance'),
('Uplifting Trance', 'uplifting_trance'),
('Orchestral Uplifting', 'orchestral_uplifting'),
('Vocal Trance', 'vocal_trance'),
('Trap', 'trap'),
('Disney', 'disney'),
('Easy Listening', 'easy_listening'),
('Background', 'background'),
('Bop', 'bop'),
('Elevator', 'elevator'),
('Furniture', 'furniture'),
('Lounge', 'lounge'),
('Middle of the Road', 'middle_of_the_road'),
('Swing', 'swing'),
('Electronic', 'electronic'),
('2-Step', '2step'),
('Thx Ran’dom Haug', 'thx_random_haug'),
('8bit', '8bit'),
('Bitpop & Chiptune', 'bitpop_chiptune'),
('Ambient', 'ambient'),
('Ambient Dub', 'ambient_dub'),
('Ambient House', 'ambient_house'),
('Ambient Techno', 'ambient_techno'),
('Dark Ambient', 'dark_ambient'),
('Drone Music', 'drone_music'),
('Illbient', 'illbient'),
('Isolationism', 'isolationism'),
('Lowercase', 'lowercase'),
('Asian Underground', 'asian_underground'),
('Bassline', 'bassline'),
('Chillwave', 'chillwave'),
('Chiptune', 'chiptune'),
('Bitpop', 'bitpop'),
('Game Boy', 'game_boy'),
('Nintendocore', 'nintendocore'),
('Video Game Music', 'video_game_music'),
('Yorkshire Bleeps & Bass', 'yorkshire_bleeps__bass'),
('Crunk', 'crunk'),
('Downtempo', 'downtempo'),
('Acid Jazz', 'acid_jazz'),
('Balearic Beat', 'balearic_beat'),
('Chill Out', 'chill_out'),
('Dub Music', 'dub_music'),
('Dubtronica', 'dubtronica'),
('Ethnic Electronic', 'ethnic_electronic'),
('Moombahton', 'moombahton'),
('Nu Jazz', 'nu_jazz'),
('Trip Hop', 'trip_hop'),
('Drum & Bass', 'drum__bass'),
('Darkcore', 'darkcore'),
('Darkstep', 'darkstep'),
('Drumfunk', 'drumfunk'),
('Drumstep', 'drumstep'),
('Hardstep', 'hardstep'),
('Intelligent Drum & Bass', 'intelligent_drum__bass'),
('Jump-Up', 'jumpup'),
('Liquid Funk', 'liquid_funk'),
('Neurofunk', 'neurofunk'),
('Oldschool Jungle', 'oldschool_jungle'),
('Darkside Jungle', 'darkside_jungle'),
('Ragga Jungle', 'ragga_jungle'),
('Raggacore', 'raggacore'),
('Sambass', 'sambass'),
('Techstep', 'techstep'),
('Electro', 'electro'),
('Electro Backbeat', 'electro_backbeat'),
('Electro-Grime', 'electrogrime'),
('Electropop', 'electropop'),
('Electro-swing', 'electroswing'),
('Electroacoustic', 'electroacoustic'),
('Acousmatic Music', 'acousmatic_music'),
('Computer Music', 'computer_music'),
('Electroacoustic Improvisation', 'electroacoustic_improvisation'),
('Field Recording', 'field_recording'),
('Live Coding', 'live_coding'),
('Live Electronics', 'live_electronics'),
('Soundscape Composition', 'soundscape_composition'),
('Tape Music', 'tape_music'),
('Berlin School', 'berlin_school'),
('Electronic Art Music', 'electronic_art_music'),
('Electronic Dance Music', 'electronic_dance_music'),
('Folktronica', 'folktronica'),
('Freestyle Music', 'freestyle_music'),
('Glitch', 'glitch'),
('Idm', 'idm'),
('Laptronica', 'laptronica'),
('Skweee', 'skweee'),
('Sound Art', 'sound_art'),
('Synthcore', 'synthcore'),
('Electronic Rock', 'electronic_rock'),
('Alternative Dance', 'alternative_dance'),
('Baggy', 'baggy'),
('Madchester', 'madchester'),
('Dance-Punk', 'dancepunk'),
('Dance-Rock', 'dancerock'),
('Dark Wave', 'dark_wave'),
('Electroclash', 'electroclash'),
('Electronicore', 'electronicore'),
('Electropunk', 'electropunk'),
('Ethereal Wave', 'ethereal_wave'),
('Indietronica', 'indietronica'),
('New Rave', 'new_rave'),
('Space Rock', 'space_rock'),
('Synthpop', 'synthpop'),
('Synthpunk', 'synthpunk'),
('Eurodance', 'eurodance'),
('Bubblegum Dance', 'bubblegum_dance'),
('Italo Dance', 'italo_dance'),
('Turbofolk', 'turbofolk'),
('Eurobeat', 'eurobeat'),
('Hard Nrg', 'hard_nrg'),
('New Beat', 'new_beat'),
('Industrial', 'industrial'),
('Vaporwave', 'vaporwave'),
('Hyponagogic', 'hyponagogic'),
('Vektroid', 'vektroid'),
('Mallsoft', 'mallsoft'),
('Vaportrap', 'vaportrap'),
('Vaporhop', 'vaporhop'),
('Protovapor', 'protovapor'),
('UK Garage', 'uk_garage'),
('4×4', '44'),
('Speed Garage', 'speed_garage'),
('Enka', 'enka'),
('French Pop', 'french_pop'),
('American Folk Revival', 'american_folk_revival'),
('Anti-Folk', 'antifolk'),
('British Folk Revival', 'british_folk_revival'),
('Contemporary Folk', 'contemporary_folk'),
('Filk Music', 'filk_music'),
('Freak Folk', 'freak_folk'),
('Indie Folk', 'indie_folk'),
('Industrial Folk', 'industrial_folk'),
('Neofolk', 'neofolk'),
('Progressive Folk', 'progressive_folk'),
('Psychedelic Folk', 'psychedelic_folk'),
('Sung Poetry', 'sung_poetry'),
('Techno-Folk', 'technofolk'),
('German Folk', 'german_folk'),
('German Pop', 'german_pop'),
('Fitness & Workout', 'fitness__workout'),
('Alternative Rap', 'alternative_rap'),
('Bounce', 'bounce'),
('Scouse House', 'scouse_house'),
('Chap Hop', 'chap_hop'),
('Christian Hip Hop', 'christian_hip_hop'),
('Conscious Hip Hop', 'conscious_hip_hop'),
('Country-Rap', 'countryrap'),
('Grunk', 'grunk'),
('Crunkcore', 'crunkcore'),
('Cumbia Rap', 'cumbia_rap'),
('Dirty South', 'dirty_south'),
('East Coast', 'east_coast'),
('Brick City Club', 'brick_city_club'),
('Hardcore Hip Hop', 'hardcore_hip_hop'),
('Mafioso Rap', 'mafioso_rap'),
('New Jersey Hip Hop', 'new_jersey_hip_hop'),
('Freestyle Rap', 'freestyle_rap'),
('G-Funk', 'gfunk'),
('Gangsta Rap', 'gangsta_rap'),
('Golden Age', 'golden_age'),
('Hardcore Rap', 'hardcore_rap'),
('Hip-Hop', 'hiphop'),
('Hip Pop', 'hip_pop'),
('Hyphy', 'hyphy'),
('Industrial Hip Hop', 'industrial_hip_hop'),
('Instrumental Hip Hop', 'instrumental_hip_hop'),
('Jazz Rap', 'jazz_rap'),
('Latin Rap', 'latin_rap'),
('Low Bap', 'low_bap'),
('Lyrical Hip Hop', 'lyrical_hip_hop'),
('Merenrap', 'merenrap'),
('Midwest Hip Hop', 'midwest_hip_hop'),
('Chicago Hip Hop', 'chicago_hip_hop'),
('Detroit Hip Hop', 'detroit_hip_hop'),
('St. Louis Hip Hop', 'st_louis_hip_hop'),
('Twin Cities Hip Hop', 'twin_cities_hip_hop'),
('Motswako', 'motswako'),
('Nerdcore', 'nerdcore'),
('New Jack Swing', 'new_jack_swing'),
('New School Hip Hop', 'new_school_hip_hop'),
('Old School Rap', 'old_school_rap'),
('Rap', 'rap'),
('Turntablism', 'turntablism'),
('Underground Rap', 'underground_rap'),
('West Coast Rap', 'west_coast_rap'),
('Holiday', 'holiday'),
('Chanukah', 'chanukah'),
('Christmas', 'christmas'),
('Easter', 'easter'),
('Halloween', 'halloween'),
('Thanksgiving', 'thanksgiving'),
('Indie Pop', 'indie_pop'),
('Aggrotech', 'aggrotech'),
('Coldwave', 'coldwave'),
('Cybergrind', 'cybergrind'),
('Dark Electro', 'dark_electro'),
('Death Industrial', 'death_industrial'),
('Electro-Industrial', 'electroindustrial'),
('Electronic Body Music', 'electronic_body_music'),
('Futurepop', 'futurepop'),
('Industrial Metal', 'industrial_metal'),
('Neue Deutsche Härte', 'neue_deutsche_harte'),
('Industrial Rock', 'industrial_rock'),
('Noise', 'noise'),
('Japanoise', 'japanoise'),
('Power Electronics', 'power_electronics'),
('Power Noise', 'power_noise'),
('Witch House', 'witch_house'),
('Inspirational', 'inspirational'),
('CCM', 'ccm'),
('Christian Metal', 'christian_metal'),
('Christian Pop', 'christian_pop'),
('Christian Rap', 'christian_rap'),
('Christian Rock', 'christian_rock'),
('Classic Christian', 'classic_christian'),
('Contemporary Gospel', 'contemporary_gospel'),
('Gospel', 'gospel'),
('Christian & Gospel', 'christian__gospel'),
('Praise & Worship', 'praise__worship'),
('Qawwali', 'qawwali'),
('Southern Gospel', 'southern_gospel'),
('Traditional Gospel', 'traditional_gospel'),
('Instrumental', 'instrumental'),
('March', 'march'),
('Marching Band', 'marching_band'),
('J-Pop', 'jpop'),
('J-Rock', 'jrock'),
('J-Synth', 'jsynth'),
('J-Ska', 'jska'),
('J-Punk', 'jpunk'),
('Jazz', 'jazz'),
('Afro-Cuban Jazz', 'afrocuban_jazz'),
('Avant-Garde Jazz', 'avantgarde_jazz'),
('Bebop', 'bebop'),
('Big Band', 'big_band'),
('Blue Note', 'blue_note'),
('British Dance Band', 'british_dance_band'),
('Cape Jazz', 'cape_jazz'),
('Chamber Jazz', 'chamber_jazz'),
('Contemporary Jazz', 'contemporary_jazz'),
('Continental Jazz', 'continental_jazz'),
('Cool Jazz', 'cool_jazz'),
('Crossover Jazz', 'crossover_jazz'),
('Dark Jazz', 'dark_jazz'),
('Dixieland', 'dixieland'),
('Early Jazz', 'early_jazz'),
('Electro Swing', 'electro_swing'),
('Ethio-jazz', 'ethiojazz'),
('Ethno-Jazz', 'ethnojazz'),
('European Free Jazz', 'european_free_jazz'),
('Free Funk', 'free_funk'),
('Avant-Garde', 'avantgarde'),
('Funk Jazz', 'funk_jazz'),
('Free Jazz', 'free_jazz'),
('Fusion', 'fusion'),
('Gypsy Jazz', 'gypsy_jazz'),
('Hard Bop', 'hard_bop'),
('Indo Jazz', 'indo_jazz'),
('Jazz-Funk', 'jazzfunk'),
('Jazz-Fusion', 'jazzfusion'),
('Jazz Rock', 'jazz_rock'),
('Kansas City Jazz', 'kansas_city_jazz'),
('Latin Jazz', 'latin_jazz'),
('M-Base Jazz', 'mbase_jazz'),
('Mainstream Jazz', 'mainstream_jazz'),
('Modal Jazz', 'modal_jazz'),
('Neo-Bop', 'neobop'),
('Neo-Swing', 'neoswing'),
('Orchestral Jazz', 'orchestral_jazz'),
('Post-Bop', 'postbop'),
('Punk Jazz', 'punk_jazz'),
('Ragtime', 'ragtime'),
('Ska Jazz', 'ska_jazz'),
('Folk', 'folk'),
('Skiffle', 'skiffle'),
('Smooth Jazz', 'smooth_jazz'),
('Soul Jazz', 'soul_jazz'),
('Swing Jazz', 'swing_jazz'),
('Straight-Ahead Jazz', 'straightahead_jazz'),
('Trad Jazz', 'trad_jazz'),
('Third Stream', 'third_stream'),
('West Coast Jazz', 'west_coast_jazz'),
('K-Pop', 'kpop'),
('Karaoke', 'karaoke'),
('Kayokyoku', 'kayokyoku'),
('Latin', 'latin'),
('Latin Rock', 'latin_rock'),
('Urban Rock', 'urban_rock'),
('Argentine Tango', 'argentine_tango'),
('Bachata', 'bachata'),
('Baithak Gana', 'baithak_gana'),
('Balada', 'balada'),
('Bolero', 'bolero'),
('Bossa Nova', 'bossa_nova'),
('Brazilian', 'brazilian'),
('Axé', 'axe'),
('Brazilian Rock', 'brazilian_rock'),
('Brega', 'brega'),
('Choro', 'choro'),
('Forró', 'forro'),
('Frevo', 'frevo'),
('Funk Carioca', 'funk_carioca'),
('Lambada', 'lambada'),
('Maracatu', 'maracatu'),
('Sertaneja', 'sertaneja'),
('Pagode', 'pagode'),
('Samba', 'samba'),
('Samba Rock', 'samba_rock'),
('Tecnobrega', 'tecnobrega'),
('Tropicalia', 'tropicalia'),
('Zouk-Lambada', 'zouklambada'),
('Chicha', 'chicha'),
('Criolla', 'criolla'),
('Contemporary Latin', 'contemporary_latin'),
('Cumbia', 'cumbia'),
('Flamenco', 'flamenco'),
('Spanish Flamenco', 'spanish_flamenco'),
('Huayno', 'huayno'),
('Joropo', 'joropo'),
('Mambo', 'mambo'),
('Mariachi', 'mariachi'),
('Merengue Típico', 'merengue_tipico'),
('New Flamenco', 'new_flamenco'),
('Flamenco Fusion', 'flamenco_fusion'),
('Portuguese Fado', 'portuguese_fado'),
('Punta', 'punta'),
('Punta Rock', 'punta_rock'),
('Ranchera', 'ranchera'),
('Raíces', 'raices'),
('Raison', 'raison'),
('Reggaeton y Hip-Hop', 'reggaeton_y_hiphop'),
('Regional Mexicano', 'regional_mexicano'),
('Salsa y Tropical', 'salsa_y_tropical'),
('Soca', 'soca'),
('Son', 'son'),
('Timba', 'timba'),
('Twoubadou', 'twoubadou'),
('Vallenato', 'vallenato'),
('Zouk', 'zouk'),
('Metal', 'metal'),
('Heavy Metal', 'heavy_metal'),
('Speed Metal', 'speed_metal'),
('Thrash Metal', 'thrash_metal'),
('Power Metal', 'power_metal'),
('Death Metal', 'death_metal'),
('Black Metal', 'black_metal'),
('Pagan Metal', 'pagan_metal'),
('Viking Metal', 'viking_metal'),
('Folk Metal', 'folk_metal'),
('Symphonic Metal', 'symphonic_metal'),
('Gothic Metal', 'gothic_metal'),
('Glam Metal', 'glam_metal'),
('Hair Metal', 'hair_metal'),
('Doom Metal', 'doom_metal'),
('Groove Metal', 'groove_metal'),
('Modern Metal', 'modern_metal'),
('Neoclassical Metal', 'neoclassical_metal'),
('New Wave Of British Heavy Metal', 'new_wave_of_british_heavy_metal'),
('Post Metal', 'post_metal'),
('Progressive Metal', 'progressive_metal'),
('Avantgarde Metal', 'avantgarde_metal'),
('Sludge', 'sludge'),
('Djent', 'djent'),
('Drone', 'drone'),
('Kawaii Metal', 'kawaii_metal'),
('Pirate Metal', 'pirate_metal'),
('Nu Metal', 'nu_metal'),
('Math Metal', 'math_metal'),
('Crossover', 'crossover'),
('Grindcore', 'grindcore'),
('Metalcore', 'metalcore'),
('Deathcore', 'deathcore'),
('Post Hardcore', 'post_hardcore'),
('Mathcore', 'mathcore'),
('New Age', 'new_age'),
('Environmental', 'environmental'),
('Healing', 'healing'),
('Meditation', 'meditation'),
('Nature', 'nature'),
('Relaxation', 'relaxation'),
('Travel', 'travel'),
('Pop', 'pop'),
('Adult Contemporary', 'adult_contemporary'),
('Arab Pop', 'arab_pop'),
('Britpop', 'britpop'),
('Bubblegum Pop', 'bubblegum_pop'),
('Chamber Pop', 'chamber_pop'),
('Chanson', 'chanson'),
('Europop', 'europop'),
('Austropop', 'austropop'),
('Balkan Pop', 'balkan_pop'),
('Latin Pop', 'latin_pop'),
('Laïkó', 'laiko'),
('Nederpop', 'nederpop'),
('Russian Pop', 'russian_pop'),
('Dance Pop', 'dance_pop'),
('Dream Pop', 'dream_pop'),
('Electro Pop', 'electro_pop'),
('Iranian Pop', 'iranian_pop'),
('Jangle Pop', 'jangle_pop'),
('Latin Ballad', 'latin_ballad'),
('Levenslied', 'levenslied'),
('Louisiana Swamp Pop', 'louisiana_swamp_pop'),
('Mexican Pop', 'mexican_pop'),
('Motorpop', 'motorpop'),
('New Romanticism', 'new_romanticism'),
('Orchestral Pop', 'orchestral_pop'),
('Pop Rap', 'pop_rap'),
('Popera', 'popera'),
('Pop Rock', 'pop_rock'),
('Pop Punk', 'pop_punk'),
('Power Pop', 'power_pop'),
('Psychedelic Pop', 'psychedelic_pop'),
('Schlager', 'schlager'),
('Soft Rock', 'soft_rock'),
('Sophisti-Pop', 'sophistipop'),
('Space Age Pop', 'space_age_pop'),
('Sunshine Pop', 'sunshine_pop'),
('Surf Pop', 'surf_pop'),
('Teen Pop', 'teen_pop'),
('Traditional Pop Music', 'traditional_pop_music'),
('Turkish Pop', 'turkish_pop'),
('Vispop', 'vispop'),
('Wonky Pop', 'wonky_pop'),
('Post-Disco', 'postdisco'),
('Boogie', 'boogie'),
('Dance-pop', 'dancepop'),
('Disco House', 'disco_house'),
('Dream House', 'dream_house'),
('Space House', 'space_house'),
('Japanese House', 'japanese_house'),
('Progressive Breaks', 'progressive_breaks'),
('Progressive Drum & Bass', 'progressive_drum__bass'),
('Progressive Techno', 'progressive_techno'),
('R&B', 'rb'),
('Beach Music', 'beach_music'),
('Disco', 'disco'),
('Doo Wop', 'doo_wop'),
('Funk', 'funk'),
('Modern Soul', 'modern_soul'),
('Motown', 'motown'),
('Neo-Soul', 'neosoul'),
('Northern Soul', 'northern_soul'),
('Psychedelic Soul', 'psychedelic_soul'),
('Quiet Storm', 'quiet_storm'),
('Soul', 'soul'),
('Southern Soul', 'southern_soul'),
('Reggae', 'reggae'),
('2-Tone', '2tone'),
('Dub', 'dub'),
('Roots Reggae', 'roots_reggae'),
('Reggae Fusion', 'reggae_fusion'),
('Reggae en Español', 'reggae_en_espanol'),
('Spanish Reggae', 'spanish_reggae'),
('Reggae 110', 'reggae_110'),
('Reggae Bultrón', 'reggae_bultron'),
('Romantic Flow', 'romantic_flow'),
('Lovers Rock', 'lovers_rock'),
('Raggamuffin', 'raggamuffin'),
('Ragga', 'ragga'),
('Dancehall', 'dancehall'),
('Ska', 'ska'),
('Rocksteady', 'rocksteady'),
('Reggae Dancehall', 'reggae_dancehall'),
('Rock', 'rock'),
('Acid Rock', 'acid_rock'),
('Adult-Oriented Rock', 'adultoriented_rock'),
('Afro Punk', 'afro_punk'),
('Adult Alternative', 'adult_alternative'),
('American Traditional Rock', 'american_traditional_rock'),
('Anatolian Rock', 'anatolian_rock'),
('Arena Rock', 'arena_rock'),
('Blues-Rock', 'bluesrock'),
('British Invasion', 'british_invasion'),
('Cock Rock', 'cock_rock'),
('Glam Rock', 'glam_rock'),
('Grind Core', 'grind_core'),
('Math Rock', 'math_rock'),
('Metal Core', 'metal_core'),
('Noise Rock', 'noise_rock'),
('Jam Bands', 'jam_bands'),
('Post Punk', 'post_punk'),
('Post Rock', 'post_rock'),
('Art Rock', 'art_rock'),
('Prog-Rock', 'progrock'),
('Psychedelic', 'psychedelic'),
('Rock & Roll', 'rock__roll'),
('Rockabilly', 'rockabilly'),
('Roots Rock', 'roots_rock'),
('Singer', 'singer'),
('Songwriter', 'songwriter'),
('Southern Rock', 'southern_rock'),
('Spazzcore', 'spazzcore'),
('Stoner Metal', 'stoner_metal'),
('duuuude', 'duuuude'),
('Surf', 'surf'),
('Technical Death Metal', 'technical_death_metal'),
('Tex-Mex', 'texmex'),
('Time Lord Rock', 'time_lord_rock'),
('Trock', 'trock'),
('Trip-hop', 'triphop'),
('Yacht Rock', 'yacht_rock'),
('Soft rock', 'soft_rock'),
('Alternative Folk', 'alternative_folk'),
('Contemporary Singer', 'contemporary_singer'),
('Contemporary Songwriter', 'contemporary_songwriter'),
('Folk-Rock', 'folkrock'),
('Love Song', 'love_song'),
('Chanson', 'chanson'),
('New Acoustic', 'new_acoustic'),
('Traditional Folk', 'traditional_folk'),
('Soundtrack', 'soundtrack'),
('Foreign Cinema', 'foreign_cinema'),
('Movie Soundtrack', 'movie_soundtrack'),
('Musicals', 'musicals'),
('Original Score', 'original_score'),
('TV Soundtrack', 'tv_soundtrack'),
('Spoken Word', 'spoken_word'),
('Tejano', 'tejano'),
('Chicano', 'chicano'),
('Classic', 'classic'),
('Conjunto', 'conjunto'),
('Conjunto Progressive', 'conjunto_progressive'),
('New Mex', 'new_mex'),
('Vocal', 'vocal'),
('A cappella', 'a_cappella'),
('Barbershop', 'barbershop'),
('Cantique', 'cantique'),
('Sacred Vocal', 'sacred_vocal'),
('Doo-wop', 'doowop'),
('Gregorian Chant', 'gregorian_chant'),
('Standards', 'standards'),
('Traditional Pop', 'traditional_pop'),
('Vocal Jazz', 'vocal_jazz'),
('Vocal Pop', 'vocal_pop'),
('Yodel', 'yodel'),
('World', 'world'),
('Africa', 'africa'),
('African Heavy Metal', 'african_heavy_metal'),
('African Hip Hop', 'african_hip_hop'),
('Afro-Beat', 'afrobeat'),
('Afro-House', 'afrohouse'),
('Afro-Pop', 'afropop'),
('Apala', 'apala'),
('Akpala', 'akpala'),
('Benga', 'benga'),
('Bikutsi', 'bikutsi'),
('Bongo Flava', 'bongo_flava'),
('Chimurenga', 'chimurenga'),
('Coupé-Décalé', 'coupedecale'),
('Fuji Music', 'fuji_music'),
('Genge', 'genge'),
('Gnawa', 'gnawa'),
('Hypnotic Trance', 'hypnotic_trance'),
('Highlife', 'highlife'),
('Hiplife', 'hiplife'),
('Isicathamiya', 'isicathamiya'),
('Jit', 'jit'),
('Jùjú', 'juju'),
('Kapuka', 'kapuka'),
('Kizomba', 'kizomba'),
('Kuduro', 'kuduro'),
('Kwaito', 'kwaito'),
('Kwela', 'kwela'),
('Lingala', 'lingala'),
('Rumba Lingala', 'rumba_lingala'),
('Congolese Rumba', 'congolese_rumba'),
('Makossa', 'makossa'),
('Maloya', 'maloya'),
('Marrabenta', 'marrabenta'),
('Mbalax', 'mbalax'),
('Mbaqanga', 'mbaqanga'),
('Mbube', 'mbube'),
('Morna', 'morna'),
('Museve', 'museve'),
('Negro Spiritual', 'negro_spiritual'),
('Palm-Wine', 'palmwine'),
('Raï', 'rai'),
('Sakara', 'sakara'),
('Sega', 'sega'),
('Seggae', 'seggae'),
('Semba', 'semba'),
('Soukous', 'soukous'),
('Taarab', 'taarab'),
('Zouglou', 'zouglou'),
('Asia', 'asia'),
('Anison', 'anison'),
('C-Pop', 'cpop'),
('CityPop', 'citypop'),
('Cantopop', 'cantopop'),
('Hong Kong English Pop', 'hong_kong_english_pop'),
('Fann At-Tanbura', 'fann_attanbura'),
('Fijiri', 'fijiri'),
('Japanese Pop', 'japanese_pop'),
('Khaliji', 'khaliji'),
('Kayōkyoku', 'kayokyoku'),
('Korean Pop', 'korean_pop'),
('Liwa', 'liwa'),
('Mandopop', 'mandopop'),
('Onkyokei', 'onkyokei'),
('Taiwanese Pop', 'taiwanese_pop'),
('T-Pop', 'tpop'),
('Thai pop', 'thai_pop'),
('Sawt', 'sawt'),
('Australia', 'australia'),
('Cajun', 'cajun'),
('Calypso', 'calypso'),
('Caribbean', 'caribbean'),
('Chutney', 'chutney'),
('Chutney Soca', 'chutney_soca'),
('Compas', 'compas'),
('Merengue', 'merengue'),
('Méringue', 'meringue'),
('Carnatic', 'carnatic'),
('Karnataka Sanghetha', 'karnataka_sanghetha'),
('Celtic', 'celtic'),
('Celtic Folk', 'celtic_folk'),
('Contemporary Celtic', 'contemporary_celtic'),
('Dangdut', 'dangdut'),
('Drinking Songs', 'drinking_songs'),
('France', 'france'),
('Hawaii', 'hawaii'),
('Japan', 'japan'),
('Klezmer', 'klezmer'),
('Middle East', 'middle_east'),
('North America', 'north_america'),
('Ode', 'ode'),
('Piphat', 'piphat'),
('Polka', 'polka'),
('South Africa', 'south_africa'),
('South America', 'south_america'),
('South Asia', 'south_asia'),
('Southeast Asia', 'southeast_asia'),
('Baila', 'baila'),
('Bhangra', 'bhangra'),
('Bhojpuri', 'bhojpuri'),
('Filmi', 'filmi'),
('Indian Pop', 'indian_pop'),
('Hindustani', 'hindustani'),
('Indian Ghazal', 'indian_ghazal'),
('Lavani', 'lavani'),
('Luk Thung', 'luk_thung'),
('Luk Krung', 'luk_krung'),
('Manila Sound', 'manila_sound'),
('Morlam', 'morlam'),
('Pinoy Pop', 'pinoy_pop'),
('Pop Sunda', 'pop_sunda'),
('Ragini', 'ragini'),
('Thai Pop', 'thai_pop'),
('Traditional Celtic', 'traditional_celtic'),
('Worldbeat', 'worldbeat')
ON CONFLICT (slug) DO NOTHING;
