-- Music genres' seed --
INSERT INTO genres (name, alt_name, slug) VALUES
('Alternative', NULL, 'alternative'),
('Art Punk', NULL, 'art_punk'),
('Alternative Rock', NULL, 'alternative_rock'),
('Britpunk', NULL, 'britpunk'),
('College Rock', NULL, 'college_rock'),
('Crossover Thrash', NULL, 'crossover_thrash'),
('Crust Punk', 'Thx Haug', 'crust_punk'),
('Emotional Hardcore', 'Emo;Emocore', 'emotional_hardcore'),
('Experimental Rock', NULL, 'experimental_rock'),
('Folk Punk', NULL, 'folk_punk'),
('Goth', 'Gothic Rock', 'goth'),
('Grunge', NULL, 'grunge'),
('Hardcore Punk', NULL, 'hardcore_punk'),
('Hard Rock', NULL, 'hard_rock'),
('Indie Rock', NULL, 'indie_rock'),
('Lo-fi', NULL, 'lofi'),
('Musique Concrète', NULL, 'musique_concrete'),
('New Wave', NULL, 'new_wave'),
('Progressive Rock', NULL, 'progressive_rock'),
('Punk', NULL, 'punk'),
('Shoegaze', NULL, 'shoegaze'),
('Steampunk', NULL, 'steampunk'),
('Anime', NULL, 'anime'),
('Blues', NULL, 'blues'),
('Acoustic Blues', NULL, 'acoustic_blues'),
('African Blues', NULL, 'african_blues'),
('Blues Rock', 'Blues Shouter', 'blues_rock'),
('British Blues', NULL, 'british_blues'),
('Canadian Blues', NULL, 'canadian_blues'),
('Chicago Blues', NULL, 'chicago_blues'),
('Classic Blues', NULL, 'classic_blues'),
('Classic Female Blues', NULL, 'classic_female_blues'),
('Contemporary Blues', NULL, 'contemporary_blues'),
('Contemporary R&B', NULL, 'contemporary_rb'),
('Country Blues', NULL, 'country_blues'),
('Dark Blues', NULL, 'dark_blues'),
('Delta Blues', NULL, 'delta_blues'),
('Detroit Blues', NULL, 'detroit_blues'),
('Doom Blues', NULL, 'doom_blues'),
('Electric Blues', NULL, 'electric_blues'),
('Folk Blues', NULL, 'folk_blues'),
('Gospel Blues', NULL, 'gospel_blues'),
('Harmonica Blues', NULL, 'harmonica_blues'),
('Hill Country Blues', NULL, 'hill_country_blues'),
('Hokum Blues', NULL, 'hokum_blues'),
('Jazz Blues', NULL, 'jazz_blues'),
('Jump Blues', NULL, 'jump_blues'),
('Kansas City Blues', NULL, 'kansas_city_blues'),
('Louisiana Blues', NULL, 'louisiana_blues'),
('Memphis Blues', NULL, 'memphis_blues'),
('Modern Blues', NULL, 'modern_blues'),
('New Orlean Blues', NULL, 'new_orlean_blues'),
('NY Blues', NULL, 'ny_blues'),
('Piano Blues', NULL, 'piano_blues'),
('Piedmont Blues', NULL, 'piedmont_blues'),
('Punk Blues', NULL, 'punk_blues'),
('Ragtime Blues', NULL, 'ragtime_blues'),
('Rhythm Blues', NULL, 'rhythm_blues'),
('Soul Blues', NULL, 'soul_blues'),
('St. Louis Blues', NULL, 'st_louis_blues'),
('Swamp Blues', NULL, 'swamp_blues'),
('Texas Blues', NULL, 'texas_blues'),
('Urban Blues', NULL, 'urban_blues'),
('Vandeville', NULL, 'vandeville'),
('West Coast Blues', NULL, 'west_coast_blues'),
('Zydeco', NULL, 'zydeco'),
('Children’s Music', NULL, 'childrens_music'),
('Lullabies', NULL, 'lullabies'),
('Sing-Along', NULL, 'singalong'),
('Stories', NULL, 'stories'),
('Classical', NULL, 'classical'),
('Avant-Garde', NULL, 'avantgarde'),
('Ballet', NULL, 'ballet'),
('Baroque', NULL, 'baroque'),
('Cantata', NULL, 'cantata'),
('Chamber Music', NULL, 'chamber_music'),
('String Quartet', NULL, 'string_quartet'),
('Chant', NULL, 'chant'),
('Choral', NULL, 'choral'),
('Classical Crossover', NULL, 'classical_crossover'),
('Concerto', NULL, 'concerto'),
('Concerto Grosso', NULL, 'concerto_grosso'),
('Contemporary Classical', NULL, 'contemporary_classical'),
('Early Music', NULL, 'early_music'),
('Expressionist', NULL, 'expressionist'),
('High Classical', NULL, 'high_classical'),
('Impressionist', NULL, 'impressionist'),
('Mass Requiem', NULL, 'mass_requiem'),
('Medieval', NULL, 'medieval'),
('Minimalism', NULL, 'minimalism'),
('Modern Composition', NULL, 'modern_composition'),
('Modern Classical', NULL, 'modern_classical'),
('Opera', NULL, 'opera'),
('Oratorio', NULL, 'oratorio'),
('Orchestral', NULL, 'orchestral'),
('Organum', NULL, 'organum'),
('Renaissance', NULL, 'renaissance'),
('Romantic', NULL, 'romantic'),
('Sonata', NULL, 'sonata'),
('Symphonic', NULL, 'symphonic'),
('Symphony', NULL, 'symphony'),
('Twelve-tone', NULL, 'twelvetone'),
('Wedding Music', NULL, 'wedding_music'),
('Comedy', NULL, 'comedy'),
('Novelty', NULL, 'novelty'),
('Parody Music', 'Weird Al!', 'parody_music'),
('Stand-up Comedy', NULL, 'standup_comedy'),
('Vaudeville', NULL, 'vaudeville'),
('Commercial', NULL, 'commercial'),
('Jingles', NULL, 'jingles'),
('TV Themes', NULL, 'tv_themes'),
('Country', NULL, 'country'),
('Alternative Country', NULL, 'alternative_country'),
('Americana', NULL, 'americana'),
('Australian Country', NULL, 'australian_country'),
('Bakersfield Sound', NULL, 'bakersfield_sound'),
('Bluegrass', NULL, 'bluegrass'),
('Progressive Bluegrass', NULL, 'progressive_bluegrass'),
('Reactionary Bluegrass', NULL, 'reactionary_bluegrass'),
('Cajun Fiddle Tunes', NULL, 'cajun_fiddle_tunes'),
('Christian Country', NULL, 'christian_country'),
('Classic Country', NULL, 'classic_country'),
('Close Harmony', NULL, 'close_harmony'),
('Contemporary Bluegrass', NULL, 'contemporary_bluegrass'),
('Contemporary Country', NULL, 'contemporary_country'),
('Country Gospel', NULL, 'country_gospel'),
('Country Pop', NULL, 'country_pop'),
('Country Rap', NULL, 'country_rap'),
('Country Rock', NULL, 'country_rock'),
('Country Soul', NULL, 'country_soul'),
('Cowboy', 'Western', 'cowboy'),
('Cowpunk', NULL, 'cowpunk'),
('Dansband', NULL, 'dansband'),
('Honky Tonk', NULL, 'honky_tonk'),
('Franco-Country', NULL, 'francocountry'),
('Gulf & Western', NULL, 'gulf__western'),
('Hellbilly Music', NULL, 'hellbilly_music'),
('Instrumental Country', NULL, 'instrumental_country'),
('Lubbock Sound', NULL, 'lubbock_sound'),
('Nashville Sound', NULL, 'nashville_sound'),
('Neotraditional Country', NULL, 'neotraditional_country'),
('Outlaw Country', NULL, 'outlaw_country'),
('Progressive', NULL, 'progressive'),
('Psychobilly', 'Punkabilly', 'psychobilly'),
('Red Dirt', NULL, 'red_dirt'),
('Sertanejo', NULL, 'sertanejo'),
('Texas County', NULL, 'texas_county'),
('Traditional Bluegrass', NULL, 'traditional_bluegrass'),
('Traditional Country', NULL, 'traditional_country'),
('Truck-Driving Country', NULL, 'truckdriving_country'),
('Urban Cowboy', NULL, 'urban_cowboy'),
('Western Swing', NULL, 'western_swing'),
('Dance', NULL, 'dance'),
('Club', 'Club Dance', 'club'),
('Breakcore', NULL, 'breakcore'),
('Breakbeat', 'Breakstep', 'breakbeat'),
('4-Beat', NULL, '4beat'),
('Acid Breaks', NULL, 'acid_breaks'),
('Baltimore Club', NULL, 'baltimore_club'),
('Big Beat', NULL, 'big_beat'),
('Breakbeat Hardcore', NULL, 'breakbeat_hardcore'),
('Broken Beat', NULL, 'broken_beat'),
('Florida Breaks', NULL, 'florida_breaks'),
('Nu Skool Breaks', NULL, 'nu_skool_breaks'),
('Brostep', NULL, 'brostep'),
('Chillstep', NULL, 'chillstep'),
('Deep House', NULL, 'deep_house'),
('Dubstep', NULL, 'dubstep'),
('Electro House', NULL, 'electro_house'),
('Electroswing', NULL, 'electroswing'),
('Exercise', NULL, 'exercise'),
('Future Garage', NULL, 'future_garage'),
('Garage', NULL, 'garage'),
('Glitch Hop', NULL, 'glitch_hop'),
('Glitch Pop', NULL, 'glitch_pop'),
('Grime', NULL, 'grime'),
('Hardcore', NULL, 'hardcore'),
('Bouncy House', NULL, 'bouncy_house'),
('Bouncy Techno', NULL, 'bouncy_techno'),
('Digital Hardcore', NULL, 'digital_hardcore'),
('Doomcore', NULL, 'doomcore'),
('Dubstyle', NULL, 'dubstyle'),
('Gabber', NULL, 'gabber'),
('Happy Hardcore', NULL, 'happy_hardcore'),
('Hardstyle', NULL, 'hardstyle'),
('Jumpstyle', NULL, 'jumpstyle'),
('Makina', NULL, 'makina'),
('Speedcore', NULL, 'speedcore'),
('Terrorcore', NULL, 'terrorcore'),
('Uk Hardcore', NULL, 'uk_hardcore'),
('Hard Dance', NULL, 'hard_dance'),
('Hi-NRG', 'Eurodance', 'hinrg'),
('Horrorcore', 'Thx Matt', 'horrorcore'),
('House', NULL, 'house'),
('Acid House', NULL, 'acid_house'),
('Chicago House', NULL, 'chicago_house'),
('Diva House', NULL, 'diva_house'),
('Dutch House', NULL, 'dutch_house'),
('Freestyle House', NULL, 'freestyle_house'),
('French House', NULL, 'french_house'),
('Funky House', NULL, 'funky_house'),
('Ghetto House', NULL, 'ghetto_house'),
('Hardbag', NULL, 'hardbag'),
('Hip House', NULL, 'hip_house'),
('Italo House', NULL, 'italo_house'),
('Latin House', NULL, 'latin_house'),
('Minimal House', NULL, 'minimal_house'),
('Progressive House', 'Trance', 'progressive_house'),
('Rave Music', NULL, 'rave_music'),
('Swing House', NULL, 'swing_house'),
('Tech House', NULL, 'tech_house'),
('Tribal House', NULL, 'tribal_house'),
('Tropical House', NULL, 'tropical_house'),
('UK Hard House', NULL, 'uk_hard_house'),
('US Garage', NULL, 'us_garage'),
('Vocal House', NULL, 'vocal_house'),
('Jackin House', NULL, 'jackin_house'),
('Jungle', 'Drum’n’bass', 'jungle'),
('Liquid Dub', NULL, 'liquid_dub'),
('Regstep', NULL, 'regstep'),
('Techno', NULL, 'techno'),
('Acid Techno', NULL, 'acid_techno'),
('Detroit Techno', NULL, 'detroit_techno'),
('Free Tekno', NULL, 'free_tekno'),
('Ghettotech', NULL, 'ghettotech'),
('Minimal', NULL, 'minimal'),
('Nortec', NULL, 'nortec'),
('Schranz', NULL, 'schranz'),
('Techno-Dnb', NULL, 'technodnb'),
('Technopop', NULL, 'technopop'),
('Tecno Brega', NULL, 'tecno_brega'),
('Toytown Techno', NULL, 'toytown_techno'),
('Trance', NULL, 'trance'),
('Acid Trance', NULL, 'acid_trance'),
('Acid-House', NULL, 'acidhouse'),
('Classic Trance', NULL, 'classic_trance'),
('Dark Psy', NULL, 'dark_psy'),
('Dream Trance', NULL, 'dream_trance'),
('Goa Trance', NULL, 'goa_trance'),
('Dark Psytrance', NULL, 'dark_psytrance'),
('Full on', NULL, 'full_on'),
('Psybreaks', NULL, 'psybreaks'),
('Psyprog', NULL, 'psyprog'),
('Suomisaundi', NULL, 'suomisaundi'),
('Hard Trance', NULL, 'hard_trance'),
('Prog. Trance', NULL, 'prog_trance'),
('Psy-Trance', NULL, 'psytrance'),
('Minimal Techno', NULL, 'minimal_techno'),
('Tech Trance', NULL, 'tech_trance'),
('Uplifting Trance', NULL, 'uplifting_trance'),
('Orchestral Uplifting', NULL, 'orchestral_uplifting'),
('Vocal Trance', NULL, 'vocal_trance'),
('Trap', NULL, 'trap'),
('Disney', NULL, 'disney'),
('Easy Listening', NULL, 'easy_listening'),
('Background', NULL, 'background'),
('Bop', NULL, 'bop'),
('Elevator', NULL, 'elevator'),
('Furniture', NULL, 'furniture'),
('Lounge', NULL, 'lounge'),
('Middle of the Road', NULL, 'middle_of_the_road'),
('Swing', NULL, 'swing'),
('Electronic', NULL, 'electronic'),
('2-Step', 'Thx Ran’dom Haug', '2step'),
('8bit', 'Bitpop & Chiptune', '8bit'),
('Ambient', NULL, 'ambient'),
('Ambient Dub', NULL, 'ambient_dub'),
('Ambient House', NULL, 'ambient_house'),
('Ambient Techno', NULL, 'ambient_techno'),
('Dark Ambient', NULL, 'dark_ambient'),
('Drone Music', NULL, 'drone_music'),
('Illbient', NULL, 'illbient'),
('Isolationism', NULL, 'isolationism'),
('Lowercase', NULL, 'lowercase'),
('Asian Underground', NULL, 'asian_underground'),
('Bassline', NULL, 'bassline'),
('Chillwave', NULL, 'chillwave'),
('Chiptune', NULL, 'chiptune'),
('Bitpop', NULL, 'bitpop'),
('Game Boy', NULL, 'game_boy'),
('Nintendocore', NULL, 'nintendocore'),
('Video Game Music', NULL, 'video_game_music'),
('Yorkshire Bleeps & Bass', NULL, 'yorkshire_bleeps__bass'),
('Crunk', NULL, 'crunk'),
('Downtempo', NULL, 'downtempo'),
('Acid Jazz', NULL, 'acid_jazz'),
('Balearic Beat', NULL, 'balearic_beat'),
('Chill Out', NULL, 'chill_out'),
('Dub Music', NULL, 'dub_music'),
('Dubtronica', NULL, 'dubtronica'),
('Ethnic Electronic', NULL, 'ethnic_electronic'),
('Moombahton', NULL, 'moombahton'),
('Nu Jazz', NULL, 'nu_jazz'),
('Trip Hop', NULL, 'trip_hop'),
('Drum & Bass', NULL, 'drum__bass'),
('Darkcore', NULL, 'darkcore'),
('Darkstep', NULL, 'darkstep'),
('Drumfunk', NULL, 'drumfunk'),
('Drumstep', NULL, 'drumstep'),
('Hardstep', NULL, 'hardstep'),
('Intelligent Drum & Bass', NULL, 'intelligent_drum__bass'),
('Jump-Up', NULL, 'jumpup'),
('Liquid Funk', NULL, 'liquid_funk'),
('Neurofunk', NULL, 'neurofunk'),
('Oldschool Jungle', NULL, 'oldschool_jungle'),
('Darkside Jungle', NULL, 'darkside_jungle'),
('Ragga Jungle', NULL, 'ragga_jungle'),
('Raggacore', NULL, 'raggacore'),
('Sambass', NULL, 'sambass'),
('Techstep', NULL, 'techstep'),
('Electro', NULL, 'electro'),
('Electro Backbeat', NULL, 'electro_backbeat'),
('Electro-Grime', NULL, 'electrogrime'),
('Electropop', NULL, 'electropop'),
('Electro-swing', NULL, 'electroswing'),
('Electroacoustic', NULL, 'electroacoustic'),
('Acousmatic Music', NULL, 'acousmatic_music'),
('Computer Music', NULL, 'computer_music'),
('Electroacoustic Improvisation', NULL, 'electroacoustic_improvisation'),
('Field Recording', NULL, 'field_recording'),
('Live Coding', NULL, 'live_coding'),
('Live Electronics', NULL, 'live_electronics'),
('Soundscape Composition', NULL, 'soundscape_composition'),
('Tape Music', NULL, 'tape_music'),
('Berlin School', NULL, 'berlin_school'),
('Electronic Art Music', NULL, 'electronic_art_music'),
('Electronic Dance Music', NULL, 'electronic_dance_music'),
('Folktronica', NULL, 'folktronica'),
('Freestyle Music', NULL, 'freestyle_music'),
('Glitch', NULL, 'glitch'),
('Idm', NULL, 'idm'),
('Laptronica', NULL, 'laptronica'),
('Skweee', NULL, 'skweee'),
('Sound Art', NULL, 'sound_art'),
('Synthcore', NULL, 'synthcore'),
('Electronic Rock', NULL, 'electronic_rock'),
('Alternative Dance', NULL, 'alternative_dance'),
('Baggy', NULL, 'baggy'),
('Madchester', NULL, 'madchester'),
('Dance-Punk', NULL, 'dancepunk'),
('Dance-Rock', NULL, 'dancerock'),
('Dark Wave', NULL, 'dark_wave'),
('Electroclash', NULL, 'electroclash'),
('Electronicore', NULL, 'electronicore'),
('Electropunk', NULL, 'electropunk'),
('Ethereal Wave', NULL, 'ethereal_wave'),
('Indietronica', NULL, 'indietronica'),
('New Rave', NULL, 'new_rave'),
('Space Rock', NULL, 'space_rock'),
('Synthpop', NULL, 'synthpop'),
('Synthpunk', NULL, 'synthpunk'),
('Eurodance', NULL, 'eurodance'),
('Bubblegum Dance', NULL, 'bubblegum_dance'),
('Italo Dance', NULL, 'italo_dance'),
('Turbofolk', NULL, 'turbofolk'),
('Eurobeat', NULL, 'eurobeat'),
('Hard Nrg', NULL, 'hard_nrg'),
('New Beat', NULL, 'new_beat'),
('Industrial', NULL, 'industrial'),
('Vaporwave', NULL, 'vaporwave'),
('Hyponagogic', NULL, 'hyponagogic'),
('Vektroid', NULL, 'vektroid'),
('Mallsoft', NULL, 'mallsoft'),
('Vaportrap', NULL, 'vaportrap'),
('Vaporhop', NULL, 'vaporhop'),
('Protovapor', NULL, 'protovapor'),
('UK Garage', NULL, 'uk_garage'),
('4×4', NULL, '44'),
('Speed Garage', NULL, 'speed_garage'),
('Enka', NULL, 'enka'),
('French Pop', NULL, 'french_pop'),
('American Folk Revival', NULL, 'american_folk_revival'),
('Anti-Folk', NULL, 'antifolk'),
('British Folk Revival', NULL, 'british_folk_revival'),
('Contemporary Folk', NULL, 'contemporary_folk'),
('Filk Music', NULL, 'filk_music'),
('Freak Folk', NULL, 'freak_folk'),
('Indie Folk', NULL, 'indie_folk'),
('Industrial Folk', NULL, 'industrial_folk'),
('Neofolk', NULL, 'neofolk'),
('Progressive Folk', NULL, 'progressive_folk'),
('Psychedelic Folk', NULL, 'psychedelic_folk'),
('Sung Poetry', NULL, 'sung_poetry'),
('Techno-Folk', NULL, 'technofolk'),
('German Folk', NULL, 'german_folk'),
('German Pop', NULL, 'german_pop'),
('Fitness & Workout', NULL, 'fitness__workout'),
('Alternative Rap', NULL, 'alternative_rap'),
('Bounce', 'Scouse House', 'bounce'),
('Chap Hop', NULL, 'chap_hop'),
('Christian Hip Hop', NULL, 'christian_hip_hop'),
('Conscious Hip Hop', NULL, 'conscious_hip_hop'),
('Country-Rap', NULL, 'countryrap'),
('Grunk', NULL, 'grunk'),
('Crunkcore', NULL, 'crunkcore'),
('Cumbia Rap', NULL, 'cumbia_rap'),
('Dirty South', NULL, 'dirty_south'),
('East Coast', NULL, 'east_coast'),
('Brick City Club', NULL, 'brick_city_club'),
('Hardcore Hip Hop', NULL, 'hardcore_hip_hop'),
('Mafioso Rap', NULL, 'mafioso_rap'),
('New Jersey Hip Hop', NULL, 'new_jersey_hip_hop'),
('Freestyle Rap', NULL, 'freestyle_rap'),
('G-Funk', NULL, 'gfunk'),
('Gangsta Rap', NULL, 'gangsta_rap'),
('Golden Age', NULL, 'golden_age'),
('Hardcore Rap', NULL, 'hardcore_rap'),
('Hip-Hop', NULL, 'hiphop'),
('Hip Pop', NULL, 'hip_pop'),
('Hyphy', NULL, 'hyphy'),
('Industrial Hip Hop', NULL, 'industrial_hip_hop'),
('Instrumental Hip Hop', NULL, 'instrumental_hip_hop'),
('Jazz Rap', NULL, 'jazz_rap'),
('Latin Rap', NULL, 'latin_rap'),
('Low Bap', NULL, 'low_bap'),
('Lyrical Hip Hop', NULL, 'lyrical_hip_hop'),
('Merenrap', NULL, 'merenrap'),
('Midwest Hip Hop', NULL, 'midwest_hip_hop'),
('Chicago Hip Hop', NULL, 'chicago_hip_hop'),
('Detroit Hip Hop', NULL, 'detroit_hip_hop'),
('St. Louis Hip Hop', NULL, 'st_louis_hip_hop'),
('Twin Cities Hip Hop', NULL, 'twin_cities_hip_hop'),
('Motswako', NULL, 'motswako'),
('Nerdcore', NULL, 'nerdcore'),
('New Jack Swing', NULL, 'new_jack_swing'),
('New School Hip Hop', NULL, 'new_school_hip_hop'),
('Old School Rap', NULL, 'old_school_rap'),
('Rap', NULL, 'rap'),
('Turntablism', NULL, 'turntablism'),
('Underground Rap', NULL, 'underground_rap'),
('West Coast Rap', NULL, 'west_coast_rap'),
('Holiday', NULL, 'holiday'),
('Chanukah', NULL, 'chanukah'),
('Christmas', NULL, 'christmas'),
('Easter', NULL, 'easter'),
('Halloween', NULL, 'halloween'),
('Thanksgiving', NULL, 'thanksgiving'),
('Indie Pop', NULL, 'indie_pop'),
('Aggrotech', NULL, 'aggrotech'),
('Coldwave', NULL, 'coldwave'),
('Cybergrind', NULL, 'cybergrind'),
('Dark Electro', NULL, 'dark_electro'),
('Death Industrial', NULL, 'death_industrial'),
('Electro-Industrial', NULL, 'electroindustrial'),
('Electronic Body Music', NULL, 'electronic_body_music'),
('Futurepop', NULL, 'futurepop'),
('Industrial Metal', NULL, 'industrial_metal'),
('Neue Deutsche Härte', NULL, 'neue_deutsche_harte'),
('Industrial Rock', NULL, 'industrial_rock'),
('Noise', NULL, 'noise'),
('Japanoise', NULL, 'japanoise'),
('Power Electronics', NULL, 'power_electronics'),
('Power Noise', NULL, 'power_noise'),
('Witch House', NULL, 'witch_house'),
('Inspirational', NULL, 'inspirational'),
('CCM', NULL, 'ccm'),
('Christian Metal', NULL, 'christian_metal'),
('Christian Pop', NULL, 'christian_pop'),
('Christian Rap', NULL, 'christian_rap'),
('Christian Rock', NULL, 'christian_rock'),
('Classic Christian', NULL, 'classic_christian'),
('Contemporary Gospel', NULL, 'contemporary_gospel'),
('Gospel', NULL, 'gospel'),
('Christian & Gospel', NULL, 'christian__gospel'),
('Praise & Worship', NULL, 'praise__worship'),
('Qawwali', NULL, 'qawwali'),
('Southern Gospel', NULL, 'southern_gospel'),
('Traditional Gospel', NULL, 'traditional_gospel'),
('Instrumental', NULL, 'instrumental'),
('March', 'Marching Band', 'march'),
('J-Pop', NULL, 'jpop'),
('J-Rock', NULL, 'jrock'),
('J-Synth', NULL, 'jsynth'),
('J-Ska', NULL, 'jska'),
('J-Punk', NULL, 'jpunk'),
('Jazz', NULL, 'jazz'),
('Afro-Cuban Jazz', NULL, 'afrocuban_jazz'),
('Avant-Garde Jazz', NULL, 'avantgarde_jazz'),
('Bebop', NULL, 'bebop'),
('Big Band', NULL, 'big_band'),
('Blue Note', NULL, 'blue_note'),
('British Dance Band', NULL, 'british_dance_band'),
('Cape Jazz', NULL, 'cape_jazz'),
('Chamber Jazz', NULL, 'chamber_jazz'),
('Contemporary Jazz', NULL, 'contemporary_jazz'),
('Continental Jazz', NULL, 'continental_jazz'),
('Cool Jazz', NULL, 'cool_jazz'),
('Crossover Jazz', NULL, 'crossover_jazz'),
('Dark Jazz', NULL, 'dark_jazz'),
('Dixieland', NULL, 'dixieland'),
('Early Jazz', NULL, 'early_jazz'),
('Electro Swing', NULL, 'electro_swing'),
('Ethio-jazz', NULL, 'ethiojazz'),
('Ethno-Jazz', NULL, 'ethnojazz'),
('European Free Jazz', NULL, 'european_free_jazz'),
('Free Funk', 'Avant-Garde;Funk Jazz', 'free_funk'),
('Free Jazz', NULL, 'free_jazz'),
('Fusion', NULL, 'fusion'),
('Gypsy Jazz', NULL, 'gypsy_jazz'),
('Hard Bop', NULL, 'hard_bop'),
('Indo Jazz', NULL, 'indo_jazz'),
('Jazz-Funk', NULL, 'jazzfunk'),
('Jazz-Fusion', NULL, 'jazzfusion'),
('Jazz Rock', NULL, 'jazz_rock'),
('Kansas City Jazz', NULL, 'kansas_city_jazz'),
('Latin Jazz', NULL, 'latin_jazz'),
('M-Base Jazz', NULL, 'mbase_jazz'),
('Mainstream Jazz', NULL, 'mainstream_jazz'),
('Modal Jazz', NULL, 'modal_jazz'),
('Neo-Bop', NULL, 'neobop'),
('Neo-Swing', NULL, 'neoswing'),
('Orchestral Jazz', NULL, 'orchestral_jazz'),
('Post-Bop', NULL, 'postbop'),
('Punk Jazz', NULL, 'punk_jazz'),
('Ragtime', NULL, 'ragtime'),
('Ska Jazz', NULL, 'ska_jazz'),
('Folk', 'Skiffle', 'folk'),
('Smooth Jazz', NULL, 'smooth_jazz'),
('Soul Jazz', NULL, 'soul_jazz'),
('Swing Jazz', NULL, 'swing_jazz'),
('Straight-Ahead Jazz', NULL, 'straightahead_jazz'),
('Trad Jazz', NULL, 'trad_jazz'),
('Third Stream', NULL, 'third_stream'),
('West Coast Jazz', NULL, 'west_coast_jazz'),
('K-Pop', NULL, 'kpop'),
('Karaoke', NULL, 'karaoke'),
('Kayokyoku', NULL, 'kayokyoku'),
('Latin', NULL, 'latin'),
('Latin Rock', NULL, 'latin_rock'),
('Urban Rock', NULL, 'urban_rock'),
('Argentine Tango', NULL, 'argentine_tango'),
('Bachata', NULL, 'bachata'),
('Baithak Gana', NULL, 'baithak_gana'),
('Balada', NULL, 'balada'),
('Bolero', NULL, 'bolero'),
('Bossa Nova', NULL, 'bossa_nova'),
('Brazilian', NULL, 'brazilian'),
('Axé', NULL, 'axe'),
('Brazilian Rock', NULL, 'brazilian_rock'),
('Brega', NULL, 'brega'),
('Choro', NULL, 'choro'),
('Forró', NULL, 'forro'),
('Frevo', NULL, 'frevo'),
('Funk Carioca', NULL, 'funk_carioca'),
('Lambada', NULL, 'lambada'),
('Maracatu', NULL, 'maracatu'),
('Sertaneja', NULL, 'sertaneja'),
('Pagode', NULL, 'pagode'),
('Samba', NULL, 'samba'),
('Samba Rock', NULL, 'samba_rock'),
('Tecnobrega', NULL, 'tecnobrega'),
('Tropicalia', NULL, 'tropicalia'),
('Zouk-Lambada', NULL, 'zouklambada'),
('Chicha', NULL, 'chicha'),
('Criolla', NULL, 'criolla'),
('Contemporary Latin', NULL, 'contemporary_latin'),
('Cumbia', NULL, 'cumbia'),
('Flamenco', 'Spanish Flamenco', 'flamenco'),
('Huayno', NULL, 'huayno'),
('Joropo', NULL, 'joropo'),
('Mambo', NULL, 'mambo'),
('Mariachi', NULL, 'mariachi'),
('Merengue Típico', NULL, 'merengue_tipico'),
('New Flamenco', 'Flamenco Fusion', 'new_flamenco'),
('Portuguese Fado', NULL, 'portuguese_fado'),
('Punta', NULL, 'punta'),
('Punta Rock', NULL, 'punta_rock'),
('Ranchera', NULL, 'ranchera'),
('Raíces', NULL, 'raices'),
('Raison', NULL, 'raison'),
('Reggaeton y Hip-Hop', NULL, 'reggaeton_y_hiphop'),
('Regional Mexicano', NULL, 'regional_mexicano'),
('Salsa y Tropical', NULL, 'salsa_y_tropical'),
('Soca', NULL, 'soca'),
('Son', NULL, 'son'),
('Timba', NULL, 'timba'),
('Twoubadou', NULL, 'twoubadou'),
('Vallenato', NULL, 'vallenato'),
('Zouk', NULL, 'zouk'),
('Metal', NULL, 'metal'),
('Heavy Metal', NULL, 'heavy_metal'),
('Speed Metal', NULL, 'speed_metal'),
('Thrash Metal', NULL, 'thrash_metal'),
('Power Metal', NULL, 'power_metal'),
('Death Metal', 'Black Metal', 'death_metal'),
('Pagan Metal', NULL, 'pagan_metal'),
('Viking Metal', NULL, 'viking_metal'),
('Folk Metal', NULL, 'folk_metal'),
('Symphonic Metal', NULL, 'symphonic_metal'),
('Gothic Metal', NULL, 'gothic_metal'),
('Glam Metal', NULL, 'glam_metal'),
('Hair Metal', NULL, 'hair_metal'),
('Doom Metal', NULL, 'doom_metal'),
('Groove Metal', NULL, 'groove_metal'),
('Modern Metal', NULL, 'modern_metal'),
('Neoclassical Metal', NULL, 'neoclassical_metal'),
('New Wave Of British Heavy Metal', NULL, 'new_wave_of_british_heavy_metal'),
('Post Metal', NULL, 'post_metal'),
('Progressive Metal', NULL, 'progressive_metal'),
('Avantgarde Metal', NULL, 'avantgarde_metal'),
('Sludge', NULL, 'sludge'),
('Djent', NULL, 'djent'),
('Drone', NULL, 'drone'),
('Kawaii Metal', NULL, 'kawaii_metal'),
('Pirate Metal', NULL, 'pirate_metal'),
('Nu Metal', NULL, 'nu_metal'),
('Math Metal', NULL, 'math_metal'),
('Crossover', NULL, 'crossover'),
('Grindcore', NULL, 'grindcore'),
('Metalcore', NULL, 'metalcore'),
('Deathcore', NULL, 'deathcore'),
('Post Hardcore', NULL, 'post_hardcore'),
('Mathcore', NULL, 'mathcore'),
('New Age', NULL, 'new_age'),
('Environmental', NULL, 'environmental'),
('Healing', NULL, 'healing'),
('Meditation', NULL, 'meditation'),
('Nature', NULL, 'nature'),
('Relaxation', NULL, 'relaxation'),
('Travel', NULL, 'travel'),
('Pop', NULL, 'pop'),
('Adult Contemporary', NULL, 'adult_contemporary'),
('Arab Pop', NULL, 'arab_pop'),
('Britpop', NULL, 'britpop'),
('Bubblegum Pop', NULL, 'bubblegum_pop'),
('Chamber Pop', NULL, 'chamber_pop'),
('Chanson', NULL, 'chanson'),
('Europop', NULL, 'europop'),
('Austropop', NULL, 'austropop'),
('Balkan Pop', NULL, 'balkan_pop'),
('Latin Pop', NULL, 'latin_pop'),
('Laïkó', NULL, 'laiko'),
('Nederpop', NULL, 'nederpop'),
('Russian Pop', NULL, 'russian_pop'),
('Dance Pop', NULL, 'dance_pop'),
('Dream Pop', NULL, 'dream_pop'),
('Electro Pop', NULL, 'electro_pop'),
('Iranian Pop', NULL, 'iranian_pop'),
('Jangle Pop', NULL, 'jangle_pop'),
('Latin Ballad', NULL, 'latin_ballad'),
('Levenslied', NULL, 'levenslied'),
('Louisiana Swamp Pop', NULL, 'louisiana_swamp_pop'),
('Mexican Pop', NULL, 'mexican_pop'),
('Motorpop', NULL, 'motorpop'),
('New Romanticism', NULL, 'new_romanticism'),
('Orchestral Pop', NULL, 'orchestral_pop'),
('Pop Rap', NULL, 'pop_rap'),
('Popera', NULL, 'popera'),
('Pop Rock', NULL, 'pop_rock'),
('Pop Punk', NULL, 'pop_punk'),
('Power Pop', NULL, 'power_pop'),
('Psychedelic Pop', NULL, 'psychedelic_pop'),
('Schlager', NULL, 'schlager'),
('Soft Rock', NULL, 'soft_rock'),
('Sophisti-Pop', NULL, 'sophistipop'),
('Space Age Pop', NULL, 'space_age_pop'),
('Sunshine Pop', NULL, 'sunshine_pop'),
('Surf Pop', NULL, 'surf_pop'),
('Teen Pop', NULL, 'teen_pop'),
('Traditional Pop Music', NULL, 'traditional_pop_music'),
('Turkish Pop', NULL, 'turkish_pop'),
('Vispop', NULL, 'vispop'),
('Wonky Pop', NULL, 'wonky_pop'),
('Post-Disco', NULL, 'postdisco'),
('Boogie', NULL, 'boogie'),
('Dance-pop', NULL, 'dancepop'),
('Disco House', NULL, 'disco_house'),
('Dream House', NULL, 'dream_house'),
('Space House', NULL, 'space_house'),
('Japanese House', NULL, 'japanese_house'),
('Progressive Breaks', NULL, 'progressive_breaks'),
('Progressive Drum & Bass', NULL, 'progressive_drum__bass'),
('Progressive Techno', NULL, 'progressive_techno'),
('R&B', NULL, 'rb'),
('Beach Music', NULL, 'beach_music'),
('Disco', NULL, 'disco'),
('Doo Wop', NULL, 'doo_wop'),
('Funk', NULL, 'funk'),
('Modern Soul', NULL, 'modern_soul'),
('Motown', NULL, 'motown'),
('Neo-Soul', NULL, 'neosoul'),
('Northern Soul', NULL, 'northern_soul'),
('Psychedelic Soul', NULL, 'psychedelic_soul'),
('Quiet Storm', NULL, 'quiet_storm'),
('Soul', NULL, 'soul'),
('Southern Soul', NULL, 'southern_soul'),
('Reggae', NULL, 'reggae'),
('2-Tone', NULL, '2tone'),
('Dub', NULL, 'dub'),
('Roots Reggae', NULL, 'roots_reggae'),
('Reggae Fusion', NULL, 'reggae_fusion'),
('Reggae en Español', NULL, 'reggae_en_espanol'),
('Spanish Reggae', NULL, 'spanish_reggae'),
('Reggae 110', NULL, 'reggae_110'),
('Reggae Bultrón', NULL, 'reggae_bultron'),
('Romantic Flow', NULL, 'romantic_flow'),
('Lovers Rock', NULL, 'lovers_rock'),
('Raggamuffin', NULL, 'raggamuffin'),
('Ragga', NULL, 'ragga'),
('Dancehall', NULL, 'dancehall'),
('Ska', NULL, 'ska'),
('Rocksteady', NULL, 'rocksteady'),
('Reggae Dancehall', NULL, 'reggae_dancehall'),
('Rock', NULL, 'rock'),
('Acid Rock', NULL, 'acid_rock'),
('Adult-Oriented Rock', NULL, 'adultoriented_rock'),
('Afro Punk', NULL, 'afro_punk'),
('Adult Alternative', NULL, 'adult_alternative'),
('American Traditional Rock', NULL, 'american_traditional_rock'),
('Anatolian Rock', NULL, 'anatolian_rock'),
('Arena Rock', NULL, 'arena_rock'),
('Blues-Rock', NULL, 'bluesrock'),
('British Invasion', NULL, 'british_invasion'),
('Cock Rock', NULL, 'cock_rock'),
('Glam Rock', NULL, 'glam_rock'),
('Grind Core', NULL, 'grind_core'),
('Math Rock', NULL, 'math_rock'),
('Metal Core', NULL, 'metal_core'),
('Noise Rock', NULL, 'noise_rock'),
('Jam Bands', NULL, 'jam_bands'),
('Post Punk', NULL, 'post_punk'),
('Post Rock', NULL, 'post_rock'),
('Art Rock', 'Prog-Rock', 'art_rock'),
('Psychedelic', NULL, 'psychedelic'),
('Rock & Roll', NULL, 'rock__roll'),
('Rockabilly', NULL, 'rockabilly'),
('Roots Rock', NULL, 'roots_rock'),
('Singer', 'Songwriter', 'singer'),
('Southern Rock', NULL, 'southern_rock'),
('Spazzcore', NULL, 'spazzcore'),
('Stoner Metal', 'duuuude', 'stoner_metal'),
('Surf', NULL, 'surf'),
('Technical Death Metal', NULL, 'technical_death_metal'),
('Tex-Mex', NULL, 'texmex'),
('Time Lord Rock', 'Trock', 'time_lord_rock'),
('Trip-hop', NULL, 'triphop'),
('Yacht Rock', 'Soft rock', 'yacht_rock'),
('Alternative Folk', NULL, 'alternative_folk'),
('Contemporary Singer', 'Contemporary Songwriter', 'contemporary_singer'),
('Folk-Rock', NULL, 'folkrock'),
('Love Song', 'Chanson', 'love_song'),
('New Acoustic', NULL, 'new_acoustic'),
('Traditional Folk', NULL, 'traditional_folk'),
('Soundtrack', NULL, 'soundtrack'),
('Foreign Cinema', NULL, 'foreign_cinema'),
('Movie Soundtrack', NULL, 'movie_soundtrack'),
('Musicals', NULL, 'musicals'),
('Original Score', NULL, 'original_score'),
('TV Soundtrack', NULL, 'tv_soundtrack'),
('Spoken Word', NULL, 'spoken_word'),
('Tejano', NULL, 'tejano'),
('Chicano', NULL, 'chicano'),
('Classic', NULL, 'classic'),
('Conjunto', NULL, 'conjunto'),
('Conjunto Progressive', NULL, 'conjunto_progressive'),
('New Mex', NULL, 'new_mex'),
('Vocal', NULL, 'vocal'),
('A cappella', NULL, 'a_cappella'),
('Barbershop', NULL, 'barbershop'),
('Cantique', 'Sacred vocal', 'cantique'),
('Doo-wop', NULL, 'doowop'),
('Gregorian Chant', NULL, 'gregorian_chant'),
('Standards', NULL, 'standards'),
('Traditional Pop', NULL, 'traditional_pop'),
('Vocal Jazz', NULL, 'vocal_jazz'),
('Vocal Pop', NULL, 'vocal_pop'),
('Yodel', NULL, 'yodel'),
('World', NULL, 'world'),
('Africa', NULL, 'africa'),
('African Heavy Metal', NULL, 'african_heavy_metal'),
('African Hip Hop', NULL, 'african_hip_hop'),
('Afro-Beat', NULL, 'afrobeat'),
('Afro-House', NULL, 'afrohouse'),
('Afro-Pop', NULL, 'afropop'),
('Apala', 'Akpala', 'apala'),
('Benga', NULL, 'benga'),
('Bikutsi', NULL, 'bikutsi'),
('Bongo Flava', NULL, 'bongo_flava'),
('Chimurenga', NULL, 'chimurenga'),
('Coupé-Décalé', NULL, 'coupedecale'),
('Fuji Music', NULL, 'fuji_music'),
('Genge', NULL, 'genge'),
('Gnawa', 'Hypnotic trance', 'gnawa'),
('Highlife', NULL, 'highlife'),
('Hiplife', NULL, 'hiplife'),
('Isicathamiya', NULL, 'isicathamiya'),
('Jit', NULL, 'jit'),
('Jùjú', NULL, 'juju'),
('Kapuka', NULL, 'kapuka'),
('Kizomba', NULL, 'kizomba'),
('Kuduro', NULL, 'kuduro'),
('Kwaito', NULL, 'kwaito'),
('Kwela', NULL, 'kwela'),
('Lingala', 'Rumba Lingala;Congolese Rumba', 'lingala'),
('Makossa', NULL, 'makossa'),
('Maloya', NULL, 'maloya'),
('Marrabenta', NULL, 'marrabenta'),
('Mbalax', NULL, 'mbalax'),
('Mbaqanga', NULL, 'mbaqanga'),
('Mbube', NULL, 'mbube'),
('Morna', NULL, 'morna'),
('Museve', NULL, 'museve'),
('Negro Spiritual', NULL, 'negro_spiritual'),
('Palm-Wine', NULL, 'palmwine'),
('Raï', NULL, 'rai'),
('Sakara', NULL, 'sakara'),
('Sega', NULL, 'sega'),
('Seggae', NULL, 'seggae'),
('Semba', NULL, 'semba'),
('Soukous', NULL, 'soukous'),
('Taarab', NULL, 'taarab'),
('Zouglou', NULL, 'zouglou'),
('Asia', NULL, 'asia'),
('Anison', NULL, 'anison'),
('C-Pop', NULL, 'cpop'),
('CityPop', NULL, 'citypop'),
('Cantopop', NULL, 'cantopop'),
('Hong Kong English Pop', NULL, 'hong_kong_english_pop'),
('Fann At-Tanbura', NULL, 'fann_attanbura'),
('Fijiri', NULL, 'fijiri'),
('Japanese Pop', NULL, 'japanese_pop'),
('Khaliji', NULL, 'khaliji'),
('Kayōkyoku', NULL, 'kayokyoku'),
('Korean Pop', NULL, 'korean_pop'),
('Liwa', NULL, 'liwa'),
('Mandopop', NULL, 'mandopop'),
('Onkyokei', NULL, 'onkyokei'),
('Taiwanese Pop', NULL, 'taiwanese_pop'),
('T-Pop', 'Thai pop', 'tpop'),
('Sawt', NULL, 'sawt'),
('Australia', NULL, 'australia'),
('Cajun', NULL, 'cajun'),
('Calypso', NULL, 'calypso'),
('Caribbean', NULL, 'caribbean'),
('Chutney', NULL, 'chutney'),
('Chutney Soca', NULL, 'chutney_soca'),
('Compas', NULL, 'compas'),
('Merengue', NULL, 'merengue'),
('Méringue', NULL, 'meringue'),
('Carnatic', 'Karnataka Sanghetha', 'carnatic'),
('Celtic', NULL, 'celtic'),
('Celtic Folk', NULL, 'celtic_folk'),
('Contemporary Celtic', NULL, 'contemporary_celtic'),
('Dangdut', NULL, 'dangdut'),
('Drinking Songs', NULL, 'drinking_songs'),
('France', NULL, 'france'),
('Hawaii', NULL, 'hawaii'),
('Japan', NULL, 'japan'),
('Klezmer', NULL, 'klezmer'),
('Middle East', NULL, 'middle_east'),
('North America', NULL, 'north_america'),
('Ode', NULL, 'ode'),
('Piphat', NULL, 'piphat'),
('Polka', NULL, 'polka'),
('South Africa', NULL, 'south_africa'),
('South America', NULL, 'south_america'),
('South Asia', 'Southeast Asia', 'south_asia'),
('Baila', NULL, 'baila'),
('Bhangra', NULL, 'bhangra'),
('Bhojpuri', NULL, 'bhojpuri'),
('Filmi', NULL, 'filmi'),
('Indian Pop', NULL, 'indian_pop'),
('Hindustani', NULL, 'hindustani'),
('Indian Ghazal', NULL, 'indian_ghazal'),
('Lavani', NULL, 'lavani'),
('Luk Thung', NULL, 'luk_thung'),
('Luk Krung', NULL, 'luk_krung'),
('Manila Sound', NULL, 'manila_sound'),
('Morlam', NULL, 'morlam'),
('Pinoy Pop', NULL, 'pinoy_pop'),
('Pop Sunda', NULL, 'pop_sunda'),
('Ragini', NULL, 'ragini'),
('Thai Pop', NULL, 'thai_pop'),
('Traditional Celtic', NULL, 'traditional_celtic'),
('Worldbeat', NULL, 'worldbeat')
ON CONFLICT (slug) DO NOTHING;
