services:
  postgres-db:
    container_name: cs-pgdb
    image: postgres:18-alpine
    expose:
      - "${DB_PORT}"
    networks:
      - cs_net
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/18/docker
  valkey-caching:
    container_name: cs-vkcache
    image: valkey/valkey:9.1-alpine
    expose:
      - "${CACHE_PORT}"
    networks:
      - cs_net
    volumes:
      - vkdata:/data
    command: valkey-server --maxmemory 256mb \
      --maxmemory-policy allkeys-lfu
  golang-api:
    container_name: cs-goapi
    expose:
      - "${API_PORT}"
    build:
      context: ./backend/
      dockerfile: Dockerfile
      target: production
      args:
        - API_PORT=${API_PORT}
    networks:
      - cs_net
    environment:
      - API_PORT=${API_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - CACHE_PORT=${CACHE_PORT}
    depends_on:
      - postgres-db
      - valkey-caching

volumes:
  pgdata:
  vkdata:

networks:
  cs_net:
    driver: bridge
