version: "3.8"

services:
  postgres-db:
    container_name: cs-pgdb
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./database:/docker-entrypoint-initdb.d:ro
      - pgdata:/var/lib/postgresql/18/docker

volumes:
  pgdata:
